name: Deploy to Local Server via Ngrok SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}  # Use your Ngrok public host here (e.g., 2856-106-51-223-27.ngrok-free.app)
          port: ${{ secrets.SSH_PORT }}  # Use the SSH port provided by Ngrok
          username: ${{ secrets.SSH_USERNAME }}  # Use your machine's username (e.g., ubuntu)
          key: ${{ secrets.SSH_KEY }}  # Your private SSH key
          script: |
            cd /path/to/your/project  # Update with your project directory path
            git pull origin main  # Pull the latest changes from `main`
            npm install  # Install dependencies
            pm2 restart my-backend  # Restart the app with PM2
